# Generated by Django 4.0.6 on 2022-08-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.userproduct'),
        ),
    ]
