# Generated by Django 4.0.6 on 2022-08-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribe',
        ),
    ]
